--- function to render circle
-- function renderer.circle(x, y, radius, segments, color)
--     local t, pixel = {}, 1
--     for i = 0, segments do
--         local a = (math.pi * 2.0) * (i / segments)
--         t[pixel] = string.char(math.floor(x + math.sin(a) * radius), math.floor(y + math.cos(a) * radius), color[1], color[2], color[3], color[4])
--         pixel = pixel + 1
--     end
--     draw.SetTexture(-1)
--     draw.TexTriangles(table.concat(t), pixel - 1)
-- end

--- function to render hsl color picker